
version: '2.4'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 40s
      retries: 10

  date_filter_0:
    build:
      context: .
      dockerfile: date_filter/Dockerfile
    environment:
      HOSTNAME: date_filter_0
    command: python3 -u ./date_filter.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  date_filter_1:
    build:
      context: .
      dockerfile: date_filter/Dockerfile
    environment:
      HOSTNAME: date_filter_1
    command: python3 -u ./date_filter.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  date_filter_2:
    build:
      context: .
      dockerfile: date_filter/Dockerfile
    environment:
      HOSTNAME: date_filter_2
    command: python3 -u ./date_filter.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  date_filter_terminator_0:
    build:
      context: .
      dockerfile: terminator/Dockerfile
    environment:
      PROCESSES_NUMBER: 1
      IN_EXCHANGE: date_filter_terminator
      GROUP_EXCHANGE: matches
      GROUP_EXCHANGE_TYPE: fanout
      GROUP_ROUTING_KEY: ''
      NEXT_EXCHANGE: filtered
      NEXT_EXCHANGE_TYPE: direct
      NEXT_ROUTING_KEYS: dispatcher-joiner
      HOSTNAME: date_filter_terminator_0
    command: python3 -u ./terminator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  surface_dispatcher_0:
    build:
      context: .
      dockerfile: surface_dispatcher/Dockerfile
    command: python3 -u ./surface_dispatcher.py
    environment:
      HOSTNAME: surface_dispatcher_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  surface_dispatcher_1:
    build:
      context: .
      dockerfile: surface_dispatcher/Dockerfile
    command: python3 -u ./surface_dispatcher.py
    environment:
      HOSTNAME: surface_dispatcher_1
    depends_on:
      rabbitmq:
        condition: service_healthy

  surface_dispatcher_2:
    build:
      context: .
      dockerfile: surface_dispatcher/Dockerfile
    command: python3 -u ./surface_dispatcher.py
    environment:
      HOSTNAME: surface_dispatcher_2
    depends_on:
      rabbitmq:
        condition: service_healthy

  surface_dispatcher_terminator_0:
    build:
      context: .
      dockerfile: terminator/Dockerfile
    environment:
      PROCESSES_NUMBER: 3
      IN_EXCHANGE: dispatcher_terminator
      GROUP_EXCHANGE: filtered
      GROUP_EXCHANGE_TYPE: direct
      GROUP_ROUTING_KEY: dispatcher
      NEXT_EXCHANGE: surfaces
      NEXT_EXCHANGE_TYPE: direct
      NEXT_ROUTING_KEYS: Hard-Clay-Grass
      HOSTNAME: surface_dispatcher_terminator_0
    command: python3 -u ./terminator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  hard_accumulator_0:
    build:
      context: .
      dockerfile: accumulator/Dockerfile
    environment:
      ROUTING_KEY: Hard
      EXCHANGE: surfaces
      OUTPUT_EXCHANGE: surface_values
      HOSTNAME: hard_accumulator_0
    command: python3 -u ./accumulator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  clay_accumulator_0:
    build:
      context: .
      dockerfile: accumulator/Dockerfile
    environment:
      ROUTING_KEY: Clay
      EXCHANGE: surfaces
      OUTPUT_EXCHANGE: surface_values
      HOSTNAME: clay_accumulator_0
    command: python3 -u ./accumulator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  grass_carpet_accumulator_0:
    build:
      context: .
      dockerfile: accumulator/Dockerfile
    environment:
      ROUTING_KEY: Grass-Carpet
      EXCHANGE: surfaces
      OUTPUT_EXCHANGE: surface_values
      HOSTNAME: grass_carpet_accumulator_0
    command: python3 -u ./accumulator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  average_calculator_0:
    build:
      context: .
      dockerfile: average_calculator/Dockerfile
    command: python3 -u ./average_calculator.py
    environment:
      HOSTNAME: average_calculator_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  joiner_0:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    command: python3 -u ./joiner.py
    environment:
      HOSTNAME: joiner_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  joiner_1:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    command: python3 -u ./joiner.py
    environment:
      HOSTNAME: joiner_1
    depends_on:
      rabbitmq:
        condition: service_healthy

  joiner_2:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    command: python3 -u ./joiner.py
    environment:
      HOSTNAME: joiner_2
    depends_on:
      rabbitmq:
        condition: service_healthy

  joiner_terminator_0:
    build:
      context: .
      dockerfile: terminator/Dockerfile
    environment:
      PROCESSES_NUMBER: 3
      IN_EXCHANGE: joiner_terminator
      GROUP_EXCHANGE: filtered
      GROUP_EXCHANGE_TYPE: direct
      GROUP_ROUTING_KEY: joiner
      NEXT_EXCHANGE: joined
      NEXT_EXCHANGE_TYPE: direct
      NEXT_ROUTING_KEYS: filter-calculator
      HOSTNAME: joiner_terminator_0
    command: python3 -u ./terminator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_calculator_0:
    build:
      context: .
      dockerfile: age_calculator/Dockerfile
    command: python3 -u ./age_calculator.py
    environment:
      HOSTNAME: age_calculator_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_calculator_1:
    build:
      context: .
      dockerfile: age_calculator/Dockerfile
    command: python3 -u ./age_calculator.py
    environment:
      HOSTNAME: age_calculator_1
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_calculator_2:
    build:
      context: .
      dockerfile: age_calculator/Dockerfile
    command: python3 -u ./age_calculator.py
    environment:
      HOSTNAME: age_calculator_2
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_calculator_terminator_0:
    build:
      context: .
      dockerfile: terminator/Dockerfile
    environment:
      PROCESSES_NUMBER: 3
      IN_EXCHANGE: calculator_terminator
      GROUP_EXCHANGE: joined
      GROUP_EXCHANGE_TYPE: direct
      GROUP_ROUTING_KEY: calculator
      NEXT_EXCHANGE: player_age
      NEXT_EXCHANGE_TYPE: fanout
      NEXT_ROUTING_KEYS: ''
      HOSTNAME: age_calculator_terminator_0
    command: python3 -u ./terminator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_difference_filter_0:
    build:
      context: .
      dockerfile: age_difference_filter/Dockerfile
    command: python3 -u ./age_difference_filter.py
    environment:
      HOSTNAME: age_difference_filter_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_difference_filter_1:
    build:
      context: .
      dockerfile: age_difference_filter/Dockerfile
    command: python3 -u ./age_difference_filter.py
    environment:
      HOSTNAME: age_difference_filter_1
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_difference_filter_2:
    build:
      context: .
      dockerfile: age_difference_filter/Dockerfile
    command: python3 -u ./age_difference_filter.py
    environment:
      HOSTNAME: age_difference_filter_2
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_difference_filter_terminator_0:
    build:
      context: .
      dockerfile: terminator/Dockerfile
    environment:
      PROCESSES_NUMBER: 3
      IN_EXCHANGE: age_filter_terminator
      GROUP_EXCHANGE: player_age
      GROUP_EXCHANGE_TYPE: fanout
      GROUP_ROUTING_KEY: ''
      NEXT_EXCHANGE: database
      NEXT_EXCHANGE_TYPE: direct
      NEXT_ROUTING_KEYS: age
      HOSTNAME: age_difference_filter_terminator_0
    command: python3 -u ./terminator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  different_hands_filter_0:
    build:
      context: .
      dockerfile: different_hands_filter/Dockerfile
    command: python3 -u ./different_hands_filter.py
    environment:
      HOSTNAME: different_hands_filter_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  different_hands_filter_1:
    build:
      context: .
      dockerfile: different_hands_filter/Dockerfile
    command: python3 -u ./different_hands_filter.py
    environment:
      HOSTNAME: different_hands_filter_1
    depends_on:
      rabbitmq:
        condition: service_healthy

  different_hands_filter_2:
    build:
      context: .
      dockerfile: different_hands_filter/Dockerfile
    command: python3 -u ./different_hands_filter.py
    environment:
      HOSTNAME: different_hands_filter_2
    depends_on:
      rabbitmq:
        condition: service_healthy

  different_hands_filter_terminator_0:
    build:
      context: .
      dockerfile: terminator/Dockerfile
    environment:
      PROCESSES_NUMBER: 3
      IN_EXCHANGE: hands_filter_terminator
      GROUP_EXCHANGE: joined
      GROUP_EXCHANGE_TYPE: direct
      GROUP_ROUTING_KEY: filter
      NEXT_EXCHANGE: hands
      NEXT_EXCHANGE_TYPE: direct
      NEXT_ROUTING_KEYS: R-L
      HOSTNAME: different_hands_filter_terminator_0
    command: python3 -u ./terminator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  right_accumulator_0:
    build:
      context: .
      dockerfile: accumulator/Dockerfile
    environment:
      ROUTING_KEY: R
      EXCHANGE: hands
      OUTPUT_EXCHANGE: hands_values
      HOSTNAME: right_accumulator_0
    command: python3 -u ./accumulator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  left_accumulator_0:
    build:
      context: .
      dockerfile: accumulator/Dockerfile
    environment:
      ROUTING_KEY: L-U
      EXCHANGE: hands
      OUTPUT_EXCHANGE: hands_values
      HOSTNAME: left_accumulator_0
    command: python3 -u ./accumulator.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  percentage_calculator_0:
    build:
      context: .
      dockerfile: percentage_calculator/Dockerfile
    command: python3 -u ./percentage_calculator.py
    environment:
      HOSTNAME: percentage_calculator_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  client_0:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      HOSTNAME: client_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  database_0:
    build:
      context: .
      dockerfile: database/Dockerfile
    command: python3 -u ./database.py
    environment:
      HOSTNAME: database_0
    depends_on:
      rabbitmq:
        condition: service_healthy

  watchdog_0:
    build:
      context: .
      dockerfile: watchdog/Dockerfile
    command: python3 -u ./watchdog.py
    environment:
      HOSTNAME: watchdog_0
      PID: 0
      BASEDIRNAME: tennis-statistics-ha
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      rabbitmq:
        condition: service_healthy

  watchdog_1:
    build:
      context: .
      dockerfile: watchdog/Dockerfile
    command: python3 -u ./watchdog.py
    environment:
      HOSTNAME: watchdog_1
      PID: 1
      BASEDIRNAME: tennis-statistics-ha
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      rabbitmq:
        condition: service_healthy

  watchdog_2:
    build:
      context: .
      dockerfile: watchdog/Dockerfile
    command: python3 -u ./watchdog.py
    environment:
      HOSTNAME: watchdog_2
      PID: 2
      BASEDIRNAME: tennis-statistics-ha
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      rabbitmq:
        condition: service_healthy
